### ISSUE TITLE
receiving from a room

### ISSUE THREAD

**Issue by keesj** [zuhito/node-red-contrib-rocketchat#6]
Hello,

I am able to listen to user events but do not understand how to listen to events in a room
I have tried different options

Origin type: Room 
#room find #roonmane 

- Errors processing request: Request failed with status code 400"

Origin type: Room 
#room find 

roonmane 

- Errors processing request: Request failed with status code 400"

#room flow.room return an error that msg is not defined (here) and this also makes sence.

9 Dec 10:37:37 - [error] [rocketchat-in:29cd5b1e.4d7f7c] ReferenceError: msg is not defined

https://github.com/zuhito/node-red-contrib-rocketchat/blob/master/rocketchat-in.js#L35

![char_receiver](https://user-images.githubusercontent.com/57112/101618006-add1e080-3a11-11eb-8a83-4c847ca5934a.png)

Any hints / example on receiving messages from a room?

**Comment by silveirado** [comment]
Hi @keesj, I remove the msg type option from the room field (PR #7)  this doesn't make sense, because this node generates a message, not consume them. You need to find one through the form or provide the name of the destination channel as str type. If your issue persists let me know... Best Regards, Silveira.

**Comment by keesj** [comment]
Thank you for the answer. 

I got a little confused about the type.
